##若未设置udev权限，则需要进入root用户才能启动相机结点（除虚拟相机外）
##相机
mindvision_camera:
    ros__parameters:
        camera_name: 'mv_camera'
        sn: '049080710063'
        config_path: './rm_infantry/config/048021610069.Config'
        camera_info_url: 'package://rm_infantry/config/048021610069.yaml'
        fps: 200
        best_effort_qos: true

virtual_camera:
    ros__parameters:
        camera_name: 'virtual_camera'
        sn: '048021610069'
        config_path: './rm_infantry/config/048021610069.Config'
        camera_info_url: 'package://rm_infantry/config/048021610069.yaml'
        fps: 10
        best_effort_qos: false
        video_path: './master-base/rm_cam/resource/ood_red.mp4'

daheng_camera:
    ros__parameters:
        camera_name: 'daheng_camera'
        sn: 'KN0210040024'
        config_path: './master-base/rm_cam/config/daheng_config/KN0210040024.txt'
        lut_config_path: ''
        lut_detail: [60., 2., 0.] # (!必须使用小数形式)对比度调节参数[-50-100] 伽马调节参数[0.1-10] 亮度调节参数[-150-150]
        camera_k: [1552.7, 0.0, 640.0, 0.0, 1537.9, 360.0, 0.0, 0.0, 1.0]
        camera_d: [0.0, 0.0, 0.0, 0.0, 0.0]
        fps: 100
        best_effort_qos: true

##串口
base:
    ros__parameters:
        serial_name: '/dev/ttySerial'
        serial_send: true
        serial_recv: true
        serial_bps: 1152000
        debug: false
        custom_qos: true
        imu_name: 'imu/data_raw'
        gimbal_cmd_name: 'cmd_gimbal'
        shoot_speed_name: 'shoot_speed'
        set_service_name: ['auto_aim','nahsor']
        
##自瞄
auto_aim:
    ros__parameters:
        armor_is_red: true 
        camera_name: 'mv_camera'
        imu_name: 'imu/data_raw'
        xml_path: './contrib_modules/rm_auto_aim/resource/HOG_SVM.xml'
        onnx_xml_path: './contrib_modules/rm_auto_aim/resource/lenet_with_negative.onnx'
        best_effort_qos: true
        auto_start: true
        shoot_delay: 0.5
        shoot_speed_name: 'shoot_speed'
        color_hsv: [140,150,150,  # red 1 
                    180,180,180,
                    0,150,150,     # red 2
                    60,180,180, 
                    2,4,
                    5,5,
                    2,8]
        x_offset: 0.
        y_offset: 0.
        z_offset: 0.
        pitch_offset: 0.0
        yaw_offset: -2.0
        fliter_p: 5000.0
        fliter_v: 5000.0
        fliter_R: 0.01
        shoot_air_param: 0.005

##能量机关
nahsor_node:
    ros__parameters:
        # armor_is_red: true
        camera_name: "mv_camera"
        imu_name: "imu/data_raw"
        best_effort_qos: true
        color: "red"
        auto_start: false
        shoot_delay: 0.35
        yaw_offset: 0.
        pitch_offset: 1.
        small_v: 2.5
        
        # 图像处理的阈值
        dilate_size: 4
        core_size: 3
        erode_size: 2
        low_red: [156., 100., 130.]
        up_red: [180., 255., 255.]
        low_red2: [0., 100., 130.]
        up_red2: [34., 255., 255.]
        low_blue: [80., 150., 180.]
        up_blue: [124., 255., 255.]
        armor_size_thre_: [500., 1000.]
        R_size_thre_: [400., 800.]
        max_r_angle_: 0.3

record_node:
  ros__parameters:
    camera_name: 'mv_camera'
    best_effort_qos: true
    fps: 30
    video_dir: './record'
    frame_per_file: 2000

imu_filter:
  ros__parameters:
    stateless: false
    use_mag: true
    publish_tf: true
    reverse_tf: false
    fixed_frame: "odom"
    constant_dt: 0.0
    publish_debug_topics: false
    world_frame: "enu"
    gain: 0.1
    zeta: 0.0
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.0


